name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: packages/foobar
      - run: npm publish --access public
        working-directory: packages/foobar
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
